server:
  port: 8081
  ssl:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

juniors:
  app:
    secret-key: bezKoderSecretKey
    expiration-ms: 86400000
